#priority 5
#modloaded atutils

import crafttweaker.item.IIngredient;
import crafttweaker.liquid.ILiquidStack;

import mods.embers.Melter;

// todo 消耗时间，耗电量

val recipes as IIngredient[][ILiquidStack] = {
    <liquid:sulfur> * 666 : [<ore:dustSulfur>],
    <liquid:naoh> * 666 : [<ore:dustSodiumHydroxide>],
    <liquid:koh> * 666 : [<ore:dustPotassiumHydroxide>],
    <liquid:arsenic> * 666 : [<ore:dustArsenic>],
    <liquid:bas> * 666 : [<ore:gemBoronArsenide>],
    <liquid:prismarine> * 144 : [<ore:crystalsPrismarine>, <ore:gemPrismarine>],
    <liquid:slime> * 144 : [<ore:slimeball>],
    <liquid:slime> * 1296 : [<ore:blockSlime>],
    <liquid:hard_carbon> * 144 : [<ore:ingotHardCarbon>],
    <liquid:manganese_dioxide> * 144 : [<ore:ingotLithiumManganeseDioxide>, <ore:dustManganeseDioxide>],
    <liquid:alugentum> * 144 : [<ore:dustAlugentum>],
    <liquid:lead_platinum> * 144 : [<ore:ingotLeadPlatinum>],
    <liquid:quartz> * 2664 : [<ore:blockQuartz>],
    <liquid:lapis> * 5994 : [<ore:blockLapis>],
    <liquid:diamond> * 5994 : [<ore:blockDiamond>],
    <liquid:emerald> * 5994 : [<ore:blockEmerald>],
    <liquid:obsidian> * 288 : [<ore:obsidian>],
    <liquid:obsidian> * 72 : [<ore:dustObsidian>],
    <liquid:nether_brick> * 72 : [<ore:netherrack>, <ore:ingotBrickNether>],
    <liquid:nether_brick> * 288 : [<ore:blockBrickNether>],
    <liquid:end_stone> * 288 : [<ore:endstone>],
    <liquid:end_stone> * 72 : [<ore:dustEndstone>],
    <liquid:purpur> * 288 : [<minecraft:purpur_block>],
    <liquid:purpur> * 72 : [<minecraft:chorus_fruit_popped>],
    <liquid:glowstone> * 250 : [<ore:dustGlowstone>],
    <liquid:glowstone> * 1000 : [<ore:glowstone>],
    <liquid:ender> * 250 : [<ore:enderpearl>],
    <liquid:pyrotheum> * 250 : [<ore:dustPyrotheum>],
    <liquid:cryotheum> * 250 : [<ore:dustCryotheum>],
    <liquid:aerotheum> * 250 : [<ore:dustAerotheum>],
    <liquid:petrotheum> * 250 : [<ore:dustPetrotheum>],
    <liquid:coal> * 100 : [<ore:itemCoal>],
    <liquid:coal> * 100 : [<ore:dustCharcoal>],
    <liquid:coal> * 100 : [<ore:ingotGraphite>],
    <liquid:coal> * 100 : [<ore:dustGraphite>],
    <liquid:coal> * 900 : [<ore:blockCoal>],
    <liquid:coal> * 900 : [<ore:blockGraphite>],
    <liquid:brine> * 15 : [<ore:itemSalt>],
    <liquid:water> * 1000 : [<ore:ice>],
    <liquid:water> * 1000 : [<ore:blockPackedIce>],
    <liquid:chocolate_liquor> * 144 : [<nuclearcraft:ground_cocoa_nibs>],
    <liquid:cocoa_butter> * 144 : [<ore:ingotCocoaButter>],
    <liquid:unsweetened_chocolate> * 144 : [<ore:ingotUnsweetenedChocolate>],
    <liquid:dark_chocolate> * 144 : [<ore:ingotDarkChocolate>],
    <liquid:milk_chocolate> * 144 : [<ore:ingotChocolate>],
    <liquid:sugar> * 144 : [<ore:listAllsugar>],
    <liquid:marshmallow> * 144 : [<ore:ingotMarshmallow>],
    <liquid:gelatin> * 144 : [<nuclearcraft:gelatin>],
    <liquid:electricium> * 144 : [<ore:ingotElectricium>],
    <liquid:electricium> * 144 : [<ore:dustElectricium>],
    <liquid:electricium> * 16 : [<ore:nuggetElectricium>],
    <liquid:electricium> * 1296 : [<ore:blockElectricium>],
    <liquid:skyfather> * 144 : [<ore:ingotSkyfather>],
    <liquid:skyfather> * 144 : [<ore:dustSkyfather>],
    <liquid:skyfather> * 16 : [<ore:nuggetSkyfather>],
    <liquid:skyfather> * 1296 : [<ore:blockSkyfather>],
    <liquid:mystic> * 144 : [<ore:ingotMystic>],
    <liquid:mystic> * 144 : [<ore:dustMystic>],
    <liquid:mystic> * 16 : [<ore:nuggetMystic>],
    <liquid:mystic> * 1296 : [<ore:blockMystic>],
    <liquid:steel> * 144 : [<ore:ingotSteel>],
    <liquid:steel> * 144 : [<ore:dustSteel>],
    <liquid:steel> * 1296 : [<ore:blockSteel>],
    <liquid:beryllium> * 144 : [<ore:ingotBeryllium>],
    <liquid:beryllium> * 144 : [<ore:dustBeryllium>],
    <liquid:beryllium> * 1296 : [<ore:blockBeryllium>],
    <liquid:zirconium> * 144 : [<ore:ingotZirconium>],
    <liquid:zirconium> * 144 : [<ore:dustZirconium>],
    <liquid:zirconium> * 1296 : [<ore:blockZirconium>],
    <liquid:enderium> * 144 : [<ore:ingotEnderium>],
    <liquid:enderium> * 144 : [<ore:dustEnder>],
    <liquid:enderium> * 16 : [<ore:nuggetEnderium>],
    <liquid:enderium> * 1296 : [<ore:blockEnderium>],
    <liquid:thorium> * 288 : [<ore:oreThorium>],
    <liquid:thorium> * 144 : [<ore:ingotThorium>],
    <liquid:thorium> * 144 : [<ore:dustThorium>],
    <liquid:thorium> * 1296 : [<ore:blockThorium>],
    <liquid:uranium> * 288 : [<ore:oreUranium>],
    <liquid:uranium> * 144 : [<ore:ingotUranium>],
    <liquid:uranium> * 144 : [<ore:dustUranium>],
    <liquid:uranium> * 16 : [<ore:nuggetUranium>],
    <liquid:uranium> * 1296 : [<ore:blockUranium>],
    <liquid:quartz> * 1332 : [<ore:oreQuartz>],
    <liquid:quartz> * 666 : [<ore:gemQuartz>],
    <liquid:quartz> * 666 : [<ore:dustQuartz>],
    <liquid:lapis> * 1332 : [<ore:oreLapis>],
    <liquid:lapis> * 666 : [<ore:gemLapis>],
    <liquid:lapis> * 666 : [<ore:dustLapis>],
    <liquid:diamond> * 1332 : [<ore:oreDiamond>],
    <liquid:diamond> * 666 : [<ore:gemDiamond>],
    <liquid:diamond> * 666 : [<ore:dustDiamond>],
    <liquid:diamond> * 76 : [<ore:nuggetDiamond>],
    <liquid:emerald> * 1332 : [<ore:oreEmerald>],
    <liquid:emerald> * 666 : [<ore:gemEmerald>],
    <liquid:emerald> * 76 : [<ore:nuggetEmerald>],
    <liquid:boron> * 288 : [<ore:oreBoron>],
    <liquid:boron> * 144 : [<ore:ingotBoron>],
    <liquid:boron> * 144 : [<ore:dustBoron>],
    <liquid:boron> * 1296 : [<ore:blockBoron>],
    <liquid:lithium> * 288 : [<ore:oreLithium>],
    <liquid:lithium> * 144 : [<ore:ingotLithium>],
    <liquid:lithium> * 144 : [<ore:dustLithium>],
    <liquid:lithium> * 1296 : [<ore:blockLithium>],
    <liquid:magnesium> * 288 : [<ore:oreMagnesium>],
    <liquid:magnesium> * 144 : [<ore:ingotMagnesium>],
    <liquid:magnesium> * 144 : [<ore:dustMagnesium>],
    <liquid:magnesium> * 1296 : [<ore:blockMagnesium>],
    <liquid:manganese> * 144 : [<ore:ingotManganese>],
    <liquid:manganese> * 144 : [<ore:dustManganese>],
    <liquid:manganese> * 1296 : [<ore:blockManganese>],
    <liquid:fluorite> * 666 : [<ore:gemFluorite>],
    <liquid:fluorite> * 666 : [<ore:dustFluorite>],
    <liquid:villiaumite> * 666 : [<ore:gemVilliaumite>],
    <liquid:villiaumite> * 666 : [<ore:dustVilliaumite>],
    <liquid:carobbiite> * 666 : [<ore:gemCarobbiite>],
    <liquid:carobbiite> * 666 : [<ore:dustCarobbiite>]
};

for output, inputs in recipes {
    for input in inputs {
        for Input in input.items {
            Melter.add(output, Input);
        }
    }
}
